"""Translate preserved manual coaching into bounded, non-executable semantic hypotheses."""
from pathlib import Path
import json,pprint,hashlib
ROOT=Path(__file__).resolve().parents[4];OUT=ROOT/'docs/coaching/2026-09-23-manual-score';ENGINE=ROOT.parent/'polyworld-gota-engine-20260923'
write=lambda p,d:p.write_text(json.dumps(d,indent=2)+'\n')
metrics={'Andre von Auto':{'games':192,'rejected_percent':2.0,'gold_spent':2901.3,'consumables_used':17.4,'creep_last_hit_xp':2142.2,'hero_kills':14.2},'Aaron':{'games':187,'rejected_percent':32.8,'gold_spent':2037.2,'consumables_used':12.8,'creep_last_hit_xp':1511.4,'hero_kills':10.1},'richard':{'games':190,'rejected_percent':10.3,'gold_spent':1890.7,'consumables_used':3.9,'creep_last_hit_xp':1491.5,'hero_kills':9.9},'Coach':{'games':188,'rejected_percent':34.5,'gold_spent':1976.8,'consumables_used':13.0,'creep_last_hit_xp':1543.7,'hero_kills':9.5}}
write(OUT/'screenshot-metrics.json',{'values':metrics,'source':'Five preserved user screenshots; values transcribed, not freshly fetched standings.','units':'Per-game arithmetic means except rejection share in percent. Different sample sizes; snapshot window and policy filters not bound by the screenshots.','derived_andre_vs_aaron':{'gold_spent_percent':(2901.3/2037.2-1)*100,'consumables_percent':(17.4/12.8-1)*100,'creep_last_hit_xp_percent':(2142.2/1511.4-1)*100,'hero_kills_percent':(14.2/10.1-1)*100,'rejected_percentage_point_gap':32.8-2.0}})
source='29f6d7e67252a9cc32521e5a906ec33222a5e7e3b5e59b168db5c6b20c9c9e36'
def skill(status,implementation,local,diagnostic,hosted):return {'status':status,'proposed_implementation':implementation,'practice':local,'diagnostic':diagnostic,'competitive_test':hosted}
gate='Freeze source/IR/current engine/exact rivals first. Fresh400games,50/source/context across both colors and lead/later draft. Mean score>=+10%, positive lower95% context-stratified whole-game bootstrap gain, eachcontext>=95%control, nonzero mean>=+5%, nonzero frequency preserved, score>=500 frequency strictly higher, zero source/VM/replay/XP/score failures and stable field. No sample extension or favorable class filtering after outcomes.'
ir={'schema':'gota-optimization-hypotheses/1','id':'manual_score_coaching_20260923','situation':{'game_version':'2026.9.23.1','engine_commit':'d6827a4bd3a55a46cf86f88e921f147137709c64','reference_source_sha256':source,'origin':'User manual coaching, five screenshots on September23; input-manifest.json binds exact images.','public_inputs':['Own class/rank/HP/mana/gold/items/cooldowns/attack timer','Own position, team and current target','Visible object kind/HP/position and public warnings','Public allied cover and alive structures','Return values of own accepted/rejected commands'],'evaluation_only':['Lifetime rawXP and unclamped margin','Opponent policy UUID/source identity','Hidden positions and full replay truth','Typed event rejection reasons and counterfactual outcomes','Aggregate player statistics'],
'predicates':{'spell_actionable':'Alive, unlocked, ready, charged, affordable, valid visible target, correct ability geometry and class/rank range. BASIC has no ability-range query: derive a current-engine binding and practice rounding boundaries.','safe_regeneration_window':'Missing a useful amount of HP/mana, family cooldown ready, outside own spawn, and a public cover/threat estimate supports uninterrupted recovery. A recent hit or nearby warning can invalidate it.','consumable_stock_short':'At own keep, useful stack below a bounded target, actual slot/stack capacity available, and spending preserves the selected core-item and buyback budget.','one_hit_creep_window':'Observed living enemy creep could be killed by the basic hit when it lands, using public HP history, distance, own attack timing and visible incoming damage. Prediction uncertainty must be measured.','xp_eligible_position':'Alive and within six tiles on the correct floor when a creep dies. Distinct from maximum weapon reach.','reachable_hero_finish':'Visible hero in a short, affordable damage sequence with acceptable cover, HP and retreat route; opportunity cost includes likely death, travel and forgone creepXP.','plausible_structure_finish':'Nearby exposed tower/god <=two current basic hits; barracks <=one. This exact proposed cutoff is already under a separate trial, not presumed optimal.'}},
'belief':{'screenshot_observations':metrics,'causal_status':'Screenshots generate hypotheses; they do not show that more spending causes better scores.','confounders':['Mixed/unknown policy filters and game versions','Different classes, draft roles, teams, sides and durations','Background VM validity unknown in screenshot aggregate','More earned gold permits spending; spending can be consequence rather than cause','Conditional nonzero/productive means can rise by discarding weak games'],
'verified_mechanics':{'score':'floor(max(0,lifetime XP-200*elapsed minutes)), including draft.','kill_rewards':'150hero killXP;100building last-hitXP;500XP to every teammate for enemy-god destruction.','health_potion':'30gold,120HP over10seconds; positive incoming damage interrupts recovery. Ten-second shared health-family cooldown persists.','vitality_elixir':'75gold,90instantHP; shares health-family cooldown with the health potion.','mana_potion':'45gold,90mana over10seconds; damage interrupts. Mana Elixir costs90gold for60instantmana; same resource family shares cooldown.','inventory':'Six slots, stackable consumables, own-keep shopping and no sell operation. Existing four core items + health potion + portal stack use all six slots. More item types require an explicit inventory tradeoff.','casts':'Object-targeted range rejection occurs before mana/charge/cooldown spending. Merely suppressing rejected casts does not demonstrate more DPS or XP. Basic attackTarget may initiate approach; do not apply spell rejection rules to it.','creep_metric':'Website last-hit XP is reward attributed at creep last hits, not a count or accuracy percentage. Nearby sharedXP is separate; current last hitter also participates in the85% share if eligible.'},
'current_controller_findings':['R_combat tries ready damaging spells on bestId without an ability-range guard. Coached replay has1328out-of-range rejections for Coach versus50for Andre; classes differ.','R_economy stocks up to two health potions, uses them with>=70missingHP, no threat within8tiles and no hit for>1second, and keeps a portal stack. No general mana/poison/elixir purchase/use policy exists.','A lethal-creep ranking bonus and Crossbowman XP-radius approach already exist. Additional last-hit gains require a newly demonstrated timing, opportunity or routing gap.','Druid lane recovery and earlier post-core buyback already exist. Do not silently reintroduce failed all-class retreat or unqualified instant-elixir bundles.','Unit-only targeting failed400clean games:−27.58%mean score despite more creepXP; deaths/time and lost hero/objectiveXP outweighed it.'],
'forecast_state_proposals':{'resource_runway':'Estimate useful heal/mana charges and gold reserved for continued productive play; actual return/use feedback invalidates stale estimates.','farm_opportunity':'Lagged visible wave density and recent observed eligible creep windows; no hidden future deaths or rawXP in live features.','engagement_margin':'Class/rank-aware public damage/HP/cover estimate; an uncalibrated heuristic until tested.'}},
'goal':{'primary':'Increase final individual XP-minus-time score.','joint_success':['Raise overall mean','Raise nonzero average without reducing nonzero frequency','Increase fraction of games scoring>=500','Raise productive-game score while retaining low-tail performance'],'avoid_proxy_goals':['Maximizing gold spent or items consumed','Minimizing rejected-command percentage without more effective actions','Extending games without enough additionalXP','Maximizing hero kills while feeding more valuable XP/time','Eliminating all building attacks or all retreats']},
'skill':{
'effective_spell_selection':skill('source_verified_gap; intervention_unvalidated','Generate class/slot/rank geometry from current content. Select a valid useful spell target independently of basic attack target where appropriate; keep basic timing and defensive actions. Consider bounded retry backoff from return0 without pretending the runtime exposes an error reason.',['Both colors/all10classes; inside/outside rounded range, self/area/projectile geometry, obscured/dead targets, mana/charge/cooldown checks','Assert accepted spell effects, damage/healing and no loss of basic hits; dense-scene VM budget'],['Rejected commands by type/slot/reason and opportunity; accepted releases and effective damage/healing per field minute','Separate harmless failed attempts from missed cast opportunities'],gate),
'productive_consumable_reserve':skill('proposed; verify inventory and wasted-recovery exposure first','Test bounded additional health stacks during already-required keep visits after protecting core progression and buyback reserve. Coordinate safe regeneration timing with existing recovery. Mana or instant-heal stacks require a separately stated slot tradeoff; do not assume all can fit.',['Actual purchase/stack counts at full inventory, family cooldowns and insufficient gold','Actual HP/mana restored over10seconds, interruption on damage, no double-use and immediate escape under threat','Do not expand all-class heal holds without a new discriminator from failed prior bundles'],['Per-item purchases/uses, effective HP/mana per gold, interruptions, unused stock, gold earned/spent and buyback share','Shopping/retreat minutes avoided, deaths, XP after recovery, and item/core timing by class/context'],gate),
'last_hit_opportunity_and_timing':skill('proposed; distinguish opportunity from conversion','Reuse bounded public scans and short HP history to initiate or retain the basic hit that can finish a creep. Preserve a committed windup where appropriate, keep within XP radius, and recover toward a productive visible wave after a drought. Current basic hit applies at windup; do not invent ranged-basic projectile delay.',['Responsive allied/enemy last-hit competition with exact current attack timing','HP falling before windup completes, target death/disappearance, retarget starvation, floor/XP-radius boundaries and low-HP hero threat','Mirrored tests and full600creep stress without exceeding19000instruction margin'],['Enemy creep deaths encountered per alive field minute and distinct visible one-hit windows','Last hits per eligible opportunity, creepXP within radius, sharedXP, gold and wave travel; opportunities are not inferred solely from XP totals','Attribution requires predecision public exposure; actual future deaths are evaluation-only'],gate),
'bounded_hero_engagement':skill('proposed; do not repeat deferred zero-activation close-hero rule','Prioritize an observed reachable kill over low-return chipping when public damage/cover predicts a profitable short fight. Keep a chase deadline, anti-tower guard and low-health escape; do not chase healthy distant heroes just to raise kill count.',['Reachable lethal hero versus lethal creep or finishable structure','Outnumbered/tower-covered target, lost vision, root/stun, recovery/channel priority and chase timeout','Measure activation in existing authentic-source replays before spending; prior close-hero diagnostic had0opportunities in4productive examples'],['Hero killXP per field minute, feasible engagements, kill conversion and assists separately','Deaths, XP donated to enemies, XP lost during travel/recovery, creepXP displaced and final score'],gate),
'selective_structure_finish':{'status':'running_separate_frozen_trial','source_sha256':'08987348157268b5aaf02b9c173942f2cde5866deba3064df64a15dee3db7b93','record':'../../../games/gods_of_the_arena/experiments/2026-09-23-selective-finish.md','local_validation':'802checks/16native games; actual100building/500godXP confirmed in220target scenarios. Competitive result pending.','must_not_change_midtrial':True}},
'strategy':[{'id':'S_CAST_VALID_EFFECT','when':'spell_actionable and useful effect predicted','prefer':'effective_spell_selection','for':['primary'],'status':'proposed'},{'id':'S_STOCK_PRODUCTIVE_RECOVERY','when':'consumable_stock_short during an already-required keep visit','prefer':'productive_consumable_reserve','for':['primary'],'status':'proposed'},{'id':'S_FIELD_SUSTAIN','when':'safe_regeneration_window and stocked resource can restore productive play','prefer':'use recovery and remain near a productive lane over a health-only base trip','for':['primary'],'status':'proposed; preserve required shopping/escape and prior failed-study exclusions'},{'id':'S_LAST_HIT_COMMIT','when':'one_hit_creep_window and xp_eligible_position','prefer':'last_hit_opportunity_and_timing','for':['primary'],'status':'proposed'},{'id':'S_HERO_FINISH','when':'reachable_hero_finish beats local farming opportunity cost','prefer':'bounded_hero_engagement','for':['primary'],'status':'proposed'},{'id':'S_STRUCTURE_FINISH','when':'plausible_structure_finish','prefer':'separately tested selective_structure_finish','for':['primary'],'status':'running; no manual-coaching edits to its frozen bytes'}],
'execution':{'binding':'research-hypotheses/1','executable':False,'apply_to_live_policy':False,'conversion_requirement':'After a hypothesis passes its diagnostic admission, update executable semantic IR and current binding together; regenerate BASIC through repo conversion, round-trip, practice and compare. Only validated final pairs may replace either live champion.','active_frozen_source_unchanged':'08987348157268b5aaf02b9c173942f2cde5866deba3064df64a15dee3db7b93','test_rule':gate},
'update':{'revision':1,'origin':'Manual user coaching, not model-discovered intent','priority':['Complete already-running selective-finish trial','Audit exact-current source rejection/resource/creep/hero evidence using existing200baseline games','Practice effective cast targeting and bounded consumable value','Separate last-hit opportunity from timing; admit a changed hero-engagement rule only if observed activation supports it'],'evidence':['input-manifest.json','screenshot-metrics.json','evidence/current-engine-analysis.json','../..//opponents/khors-v179/score-audit-20260923/README.md'],'status':'Suggestions prepared; engine/source facts verified, resource audit running, proposed gameplay interventions not competitively validated.'}}
analysis=json.loads((OUT/'evidence/current-engine-analysis.json').read_text())
assert analysis['complete'] and analysis['games']==200
ir['belief']['current_engine_diagnostics']={
 'selection':'All200 controls from the completed unit-farming trial; no new hosted games. All ten VMs, replay hashes, source identities, XP and integer scores verified.',
 'summary':{label:{'overall':value['overall'],'classes':value['classes']} for label,value in analysis['summary'].items()},
 'interpretation':'Andre plays only Ranger/Crossbowman; own cohort includes100melee appearances. Similar pooled field time does not imply equal opportunities, class strength or lane position. Within-class comparisons remain confounded by draft, side and team.',
 'critical_findings':['Own Crossbowman mean4041.22 versus Andre4096.08; own Ranger2610.24 versus Andre3426.58, in different case mixes. Own DeathKnight137.48 in86games; all14Vanguard games scorezero.',
 'Own health-potion use10.63/game versus Andre17.04, with actual healing921.025 versus1464.945. Consumables16.95 versus26.09 also include portals6.32 versus9.05.',
 'Own gold spent2920.35 versus4422.05; buyback spending1235.50 versus2245 accounts for1009.50 of the1501.70 gap. End gold804.425 versus1608.75 does not show Andre spending down reserves more aggressively.',
 'Own field time10.6566 versus10.8567minutes; hero kills per field minute0.9858 versus2.1724, total creepXP per field minute213.19 versus307.40. Opportunity and conversion still need predecision exposure measurement.',
 'Own rejected orders37.07% versus2.43% as means of per-game shares. Of own737.995rejections/game,732.69 are out-of-range casts. These are not proven lost spell effects.']}
ir['belief']['verified_mechanics']['automatic_spells']='Engine automatic casting is enabled for these bots. All200complete replays contain zero ActionManualSpells toggles across all ten actors. Failed manual range checks precede resource spending; automatic spell selection may still cast later. Prove additional effective casts or better targets before treating rejection suppression as a score intervention.'
ir['skill']['effective_spell_selection']['status']='missing manual range guard verified; harmful lost-opportunity mechanism unproven'
ir['skill']['effective_spell_selection']['diagnostic'].append('Reconstruct automatic and manual releases together. Admission requires missed useful effects or harmful target choice, not merely rejected commands.')
ir['situation']['predicates']['weak_melee_productivity']='Current own class has poor score support in a given role; evaluation-only class/role stratification identifies it. A live intervention must use public local threat, reach, wave opportunity and recovery inputs, not a memorized policy name or retrospective score.'
ir['strategy'].append({'id':'S_CLASS_SCOPED_ADMISSION','when':'A proposed change addresses a measured class/role failure window','prefer':'Practice and diagnose that scope, preserve demonstrated ranged behavior, then freeze a new source and prospectively test all declared contexts','for':['primary'],'status':'research rule; no outcome-driven exclusion from existing frozen trials'})
ir['update'].update(revision=2,priority=['Complete the already-frozen selective-finish verdict','Diagnose missed effective spell opportunities with automatic casting included','Measure last-hit exposure and conversion, especially weak melee roles and Ranger','Practice bounded health-stock and safe-use changes only where resource exhaustion causes a lost productive window','Admit a hero-engagement change only after observed activation and measured opportunity cost'],status='Manual suggestions and200-game diagnosis complete. Proposed gameplay interventions remain unvalidated; frozen live and trial BASIC unchanged.')
ir['update']['evidence']=[s.replace('../..//','../../') for s in ir['update']['evidence']]+['evidence/autocast-proof.json','evidence/coached-resource-comparison.json']
finish=ROOT.parent/'polyworld/tmp/gota-selective-finish59-20260923/trial/report.json'
if finish.exists():
 report=json.loads(finish.read_text());assert report['complete'] and report['games']==400
 result=report['candidates'][0]
 ir['skill']['selective_structure_finish'].update(status='complete_not_qualified',local_validation='802candidate checks,84baseline checks and16native games passed;400fresh games audited.',hosted_result={'qualified':report['deployment_qualified'],'mean_gain_percent':result['aggregate_gain_percent'],'gain_ci95_percent':result['gain_ci95_percent'],'productivity':result['productivity']},interpretation='Short-finish mechanics work, but only3structure commands activate in16candidate diagnostic games. Productive and nonzero conditional means rise while their frequencies fall; the joint acceptance rule fails. Preserve the exact bundle, do not deploy it.')
 for rule in ir['strategy']:
  if rule['id']=='S_STRUCTURE_FINISH':rule['status']='tested exact bundle did not qualify; a distinct intervention needs new evidence and a new frozen trial'
 ir['execution']['tested_frozen_source_unchanged']=ir['execution'].pop('active_frozen_source_unchanged')
 ir['update']['priority']=ir['update']['priority'][1:]
 ir['update']['status']='Manual suggestions and200-game diagnosis complete. Separate400-game selective-finish trial rejected by its frozen rule; live incumbent retained. Other proposed gameplay interventions remain unvalidated.'
write(OUT/'suggestions.ir.json',ir);(OUT/'suggestions.py').write_text('# Non-executable manual coaching hypotheses.\nMODEL = '+pprint.pformat(ir,width=110,sort_dicts=False)+'\n')
write(OUT/'engine-source-proof.json',{'engine_commit':ir['situation']['engine_commit'],'files':{n:hashlib.sha256((ENGINE/n).read_bytes()).hexdigest() for n in ['examples/gods_of_the_arena/content.nim','examples/gods_of_the_arena/sim.nim','examples/gods_of_the_arena/bots.nim','examples/gods_of_the_arena/scores.nim']},'reference_source_sha256':source,'reference_path':'examples/gods_of_the_arena/players/ir/forks/druid-lane20260923-hosted/druid-lane/policy.bas','website_definitions':['https://github.com/Metta-AI/polyworld-buff/blob/main/tools/PLAYERS.md','https://raw.githubusercontent.com/Metta-AI/polyworld-buff/main/tools/players/extract.nim']})
print(OUT)
