POLICY = {'schema': 'gota-semantic-policy/1',
 'id': 'gota_balance20260922_crossbow_draft',
 'situation': {'grounded': {'observation': 'Bassy Q16.16 decimals for fractional action coordinates, integer '
                                           'snapshot tiles and IDs; six inventory slots; shared public hero '
                                           'draft.',
                            'structure_alive': 'For structures objectAlive means exposed; positive HP means '
                                               'standing.',
                            'predicates': {'always': 'Unconditional lifecycle phase',
                                           'active': 'Alive, battle started, decision due, not channeling or '
                                                     'stunned'}},
               'notes': 'Current shared-frame host; public draft availability only. Keep original '
                        'global-coordinate controller as a tested component. The preceding mirrored '
                        'alternatives regressed on blue; hero strength and geometry must not be conflated.'},
 'belief': {'grounded': {'memory': ['crossed',
                                    'enemyX',
                                    'enemyY',
                                    'homeX',
                                    'homeY',
                                    'hurtTick',
                                    'initialized',
                                    'lane',
                                    'moveTick',
                                    'nextThink',
                                    'previousHits',
                                    'previousHp',
                                    'restock',
                                    'resumeTarget',
                                    'retreat',
                                    'scanOffset',
                                    'spawnX',
                                    'spawnY'],
                         'lifetime': 'BASIC globals start at zero per episode and persist across decisions '
                                     'and respawns. The lifecycle binding explicitly resets initialization '
                                     'and retreat state after death.',
                         'uncertainty': 'Unseen enemies are unknown. Visible targets may be masked. Only the '
                                        'draft roster, allied positions and visible opponents inform live '
                                        'choices.'},
            'claims': {'DraftIsolation': {'claim': 'Prioritizing Crossbowman alone improves patched-engine '
                                                   'score while preserving the productive blue movement '
                                                   'behavior of the deployed controller.',
                                          'status': 'untested',
                                          'evidence': []}}},
 'goal': {'Win': {'preference': 'Objective pressure supports XP production; fort outcomes are diagnostic, '
                                'while current league XP score is primary.',
                  'provenance': 'authored'},
          'Grow': {'preference': 'Earn shared XP and last-hit gold, spend legal skill points, and convert '
                                 'gold into durable combat strength.',
                   'provenance': 'authored'},
          'Survive': {'preference': 'Avoid repeated feeding, recover efficiently, and promptly return to '
                                    'productive play.',
                      'provenance': 'authored'},
          'Score': {'preference': 'Maximize the new live league score max(0, lifetime XP - 200 * elapsed '
                                  'world ticks / 1440); fort outcomes are a separate diagnostic.',
                    'provenance': 'authored'},
          'Practice': {'preference': 'Secure feasible last hits and shared XP, buy useful permanent power, '
                                     'and use safe portals for urgent defense or productive recovery.',
                       'provenance': 'authored'}},
 'skill': {'draft': {'operator': 'draftonly_draft', 'parameters': {'think_ticks': 6}},
           'timing': {'operator': 'draftonly_timing', 'parameters': {}},
           'lifecycle': {'operator': 'draftonly_lifecycle',
                         'parameters': {'buyback_seconds': 25, 'buyback_reserve': 200}},
           'observe': {'operator': 'draftonly_observe', 'parameters': {'scan_limit': 96}},
           'economy': {'operator': 'draftonly_economy', 'parameters': {'shop_gold': 500}},
           'home_portal': {'operator': 'draftonly_home_portal', 'parameters': {}},
           'recover': {'operator': 'draftonly_recover', 'parameters': {'retreat_hp': 24}},
           'tower_safety': {'operator': 'draftonly_tower_safety', 'parameters': {'tower_hp': 65}},
           'xp_close': {'operator': 'draftonly_xp_close', 'parameters': {}},
           'combat': {'operator': 'draftonly_combat', 'parameters': {'reset_recovery': 1}},
           'advance': {'operator': 'draftonly_advance', 'parameters': {}}},
 'strategy': [{'id': 'R_draft',
               'when': 'always',
               'skill': 'draft',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_timing',
               'when': 'always',
               'skill': 'timing',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_lifecycle',
               'when': 'always',
               'skill': 'lifecycle',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_observe',
               'when': 'active',
               'skill': 'observe',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_economy',
               'when': 'active',
               'skill': 'economy',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_home_portal',
               'when': 'active',
               'skill': 'home_portal',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_recover',
               'when': 'active',
               'skill': 'recover',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_tower_safety',
               'when': 'active',
               'skill': 'tower_safety',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_xp_close',
               'when': 'active',
               'skill': 'xp_close',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_combat',
               'when': 'active',
               'skill': 'combat',
               'for': ['Grow', 'Survive', 'Score', 'Practice']},
              {'id': 'R_advance',
               'when': 'active',
               'skill': 'advance',
               'for': ['Grow', 'Survive', 'Score', 'Practice']}],
 'execution': {'binding': 'gota-bassy/balance-draft-2026-09-22-r1',
               'game_version': '2026.9.22.2',
               'language': 'BASIC'},
 'update': {'revision': 1,
            'parent': 'e9243120947b76baef8a6226b290ca6db08e0dc09c9058c2757d70217c31e6f3',
            'change': {'origin': 'Follow-up discriminator after mirrored Ranger and Crossbowman fail blue '
                                 'score preservation; isolate Crossbowman draft priority'},
            'needs_review': ['belief/DraftIsolation'],
            'evidence': [{'artifact': 'games/gods_of_the_arena/experiments/2026-09-22-crossbow-draft-isolation.md'}]}}
