"""Publish a descriptive seven-layer model, preserving prior opponent studies."""
from pathlib import Path
from collections import Counter
import json,hashlib,pprint,shutil,statistics
ROOT=Path(__file__).resolve().parents[4];RAW=ROOT.parent/'polyworld/tmp/gota-khors114-audit-20260923';OUT=ROOT/'docs/opponents/khors-v114/score-audit-20260923'
read=lambda p:json.loads(p.read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,d):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,indent=2)+'\n')
def main():
    a=read(RAW/'analysis.json');rows=read(RAW/'actor-rows.json');plan=read(RAW/'plan.json');portals=read(RAW/'portal-transitions.json');ours=[r for r in rows if r['policy']!='khors'];khors=[r for r in rows if r['policy']=='khors'];own_audit=read(RAW/'own-source-summary.json')
    assert len(ours)==75 and len(khors)==39 and sum(r['commands_matched'] for r in own_audit['rows'])==5826
    OUT.mkdir(parents=True,exist_ok=True);ev=OUT/'evidence';ev.mkdir(exist_ok=True)
    for n in ['plan.json','analysis.json','actor-rows.json','verified.json','artifact-index.json','portal-transitions.json','clean-control-comparison.json','own-source-plan.json','own-source-provenance.json','own-source-summary.json','stalls-provenance.json','buff-visits.json']:
        shutil.copy2(RAW/n,ev/n)
    for n in ['snapshot.json','leaderboard.json']:
        shutil.copy2(RAW/'field-before'/n,ev/('field-'+n))
    shutil.copy2(ROOT/'docs/guides/guide-opponent-model-ir.md',OUT/'guide-snapshot.md')
    old_paths=['docs/opponents/khors-v114/replay-audit-20260922/opponent.ir.json','docs/opponents/richard-v167/replay-audit-20260922/khors_v114.ir.json','docs/opponents/khors-v114/blue-review-20260923/counter-hypothesis.ir.json']
    save(ev/'preserved-prior-models.json',{'unchanged':{n:sha(ROOT/n) for n in old_paths}})
    engine=ROOT.parent/'polyworld-gota-engine-score-20260922';game=read(RAW/'field-before/game.json')
    save(ev/'mechanics.json',{'game_version':'2026.9.22.3','engine_commit':plan['engine_commit'],'replay_version':58,'score':'max(0, lifetime_xp * 1440 - 200 * world_ticks) // 1440','raw_xp_public_to_basic':False,'public_progress_proxies':['selfLevel','selfGold','selfAttacksLanded','selfDeaths','selfTarget','worldTick','visible objects'],'host_sources':{n:sha(engine/n) for n in ['examples/gods_of_the_arena/bots.nim','examples/gods_of_the_arena/content.nim','examples/gods_of_the_arena/sim.nim','examples/gods_of_the_arena/scores.nim']},'source_availability':'No khors executable in searched local repositories. Hosted specs bind content hash to version; public metadata did not expose source. No source/private-VM claim for khors.','item_ids':{'11':'CrimsonDagger','16':'KnightArmor','18':'BattleAxe','19':'RuneCrossbow','20':'ArcaneSpellbook','21':'PortalScroll','1':'HealthPotion'},'league_score':'Per-player round mean then EMA0.15 new +0.85 previous; snapshot rounds_played74 is scored-round count, while analyzed platform round numbers are683,684,685.'})
    claims=[
      {'id':'K114_IDENTITY','status':'verified_hosted_identity','claim':'Exact khors:v114 UUID and content hash verified for all39 subject appearances on the current engine. Executable source unavailable.','evidence':['evidence/plan.json','evidence/verified.json']},
      {'id':'K114_DRAFT','status':'observed_conditional_choices','claim':'Selected Crossbowman12/12 times available; Ranger6/6 when available and Crossbowman unavailable. Lich/Druid alternatives vary when both available, so a universal fixed fallback ordering is not identified.','evidence':['evidence/actor-rows.json','evidence/analysis.json']},
      {'id':'K114_FARM','status':'observed_effects_not_intent','claim':'Mean2176.92hero XP and2325.10creep XP, versus only5.13building XP; mean basic structure damage19. Actual output strongly concentrates on heroes/creeps in this sample, but exact selection guards and intentional game extension are unknown.','evidence':['evidence/analysis.json']},
      {'id':'K114_RESOURCE','status':'observed_accepted_actions','claim':'First purchase dagger39/39; accepted core equipment follows11→16→18→19 in every observed progression, completed35/39. Potions/scrolls interleave. Our core order is already the same. Item19 is RuneCrossbow, not ArcaneSpellbook.','evidence':['evidence/analysis.json','evidence/mechanics.json']},
      {'id':'K114_PORTAL','status':'observed_typed_transitions','claim':'252portal starts:128keep-to-field completions,43field-to-keep,57keep-to-keep,23interruptions,1unfinished. Outbound mobility is a useful hypothesis; copying the whole portal behavior would also copy inefficient-looking keep-to-keep channels. Destination selection/internal guard unknown.','evidence':['evidence/portal-transitions.json']},
      {'id':'K114_LOW_TAIL','status':'observed_no_general_floor_advantage','claim':'Khors8/39zero scores and11/39under500; our combined14/75zero and21/75under500. Khors has a higher nonzero mean2842.68 versus2068.67. Low-tail repairs matter, but fewer zeroes do not explain this observed lead.','evidence':['evidence/analysis.json','evidence/actor-rows.json']},
      {'id':'K114_FAILURE_CONTEXT','status':'confounded_live_field','claim':'63/72games contain another failed VM. All khors/Aaron/Coach VMs clean. Khors earns12.54%of hero XP from slots whose VMs eventually fail; exact failure timing and intent are unidentified. Preserve all league outcomes and report9fullyclean games separately.','evidence':['evidence/analysis.json']},
      {'id':'OWN_EMPTY_ADVANCE','status':'own_source_replay_verified','claim':'Four contrasting own low-score cases reproduce5826submitted commands and every world hash. When no rule stops advance, crossed=1 keeps enemy-base goal; no public progress timeout exists. The zero-score Warlock emits109enemy-base attack-moves; the long-drought DeathKnight426. This identifies executed routing, not the causal gain of changing it.','evidence':['evidence/own-source-summary.json','../../../../examples/gods_of_the_arena/players/ir/forks/druid-lane20260923-hosted/druid-lane/policy.bas']}
    ]
    model={'schema':'gota-opponent-descriptive-ir/2','id':'khors_v114_score_audit_20260923',
      'situation':{'identity':{'owner':'ply_3d22435e-30a2-4f2a-b037-a5c249583788','label':'khors:v114','version':plan['ids']['khors'],'source_sha256_from_host_specs':plan['source_hashes']['khors'],'source_available':False},'game_version':plan['game_version'],'engine_commit':plan['engine_commit'],'authority':'Retrospective full replay truth and accepted typed events; no khors source or private memory. Separate authentic own-policy reconstruction on4contrasting cases.','selection':plan['selection'],'episodes':'evidence/plan.json','rounds':plan['rounds'],'appearances':{'khors':39,'aaron':38,'coach':37},'features':{'draft_available':'Actual pool immediately before observed accepted pick; observed from successive draft transitions.','combat_economy':'Typed hero/creep/building/god XP, damage, purchases and actions reconciled with final score.','low_score':'zero and0<score<500, frozen before new outcomes.','diagnostic_xp_drought':'30world seconds without XP; replay-only, includes preceding dead time. Raw XP is not exposed to BASIC.','healthy_field':'alive, outside own keep,HP>=60%; post-tick truth, not an identified opponent guard.','replenishment':'Same-actor portal starts and endings, with keep membership and HP at the event tick.'},'unknown':['Exact target ordering and range gates','Memory, route and retreat thresholds','Ability timing and automatic/manual responsibility','Buyback decision policy','Opponent identity recognition']},
      'belief':{'claims':claims,'forecast_validated':False,'counter_validated':False,'uncertainty':'39opponent appearances across72shared games; nine games have all clean VMs. No randomization of draft/class, no heldout online model, no causal attribution to a single skill. Scores are shared-game correlated.'},
      'goal':{'individual_xp':{'status':'analyst_hypothesis','description':'Acquire XP from heroes and creeps while sustaining repeated field participation. No evidence of an explicit internal XP-minus-time objective.'},'maintain_resources':{'status':'analyst_hypothesis','description':'Acquire core gear and refresh through potions/portals.'},'prolong_game':{'status':'unidentified','description':'Near-zero structure damage is consistent with unit-focused farming, but does not prove deliberate game prolongation.'}},
      'skill':{'DraftAvailableCarry':{'status':'observed','initiation':'Draft turn with carry available','operator':'select Crossbowman, otherwise Ranger in the observed opportunities','termination':'Accepted draft choice','evidence':'K114_DRAFT'},'FarmAndFight':{'status':'effect_profile_only','initiation':'Unknown','operator':'Deal basic and spell damage to heroes/creeps and receive XP','termination':'Unknown','evidence':'K114_FARM'},'PurchaseCoreAndRestock':{'status':'observed_accepted_sequence','initiation':'Shopping accepted at own keep; exact resource thresholds unknown','operator':'Dagger→armor→axe→RuneCrossbow, with potions and scrolls interleaved','termination':'Unknown','evidence':'K114_RESOURCE'},'PortalBetweenKeepAndField':{'status':'observed_typed_events','initiation':'Exact guard unknown','operator':'Channel portal, then complete or interrupt','termination':'Typed completion/interruption or game end','evidence':'K114_PORTAL'}},
      'strategy':[{'id':'K114_CARRY_WHEN_AVAILABLE','when':'Crossbowman is available at own draft turn','skill':'DraftAvailableCarry','for':['individual_xp'],'status':'observed12/12; no heldout forecast','priority_identified':False},{'id':'K114_FARMING_EMPHASIS','when':'Living match participation','skill':'FarmAndFight','for':['individual_xp'],'status':'aggregate effect profile; action selection guard unknown','priority_identified':False},{'id':'K114_CORE_RESTOCK','when':'Accepted shopping opportunity','skill':'PurchaseCoreAndRestock','for':['maintain_resources'],'status':'accepted item order observed; gold threshold/order among consumables unknown','priority_identified':False},{'id':'K114_OUTBOUND_MOBILITY','when':'At keep with a portal start observed','skill':'PortalBetweenKeepAndField','for':['individual_xp','maintain_resources'],'status':'transition observed; cannot infer destination value or exact trigger','priority_identified':False}],
      'execution':{'binding':'retrospective-descriptive/2','source_available':False,'proxy_usable':False,'forecast_validated':False,'compile_to_basic':False,'known_ordering':'Accepted draft and purchase subsequences only. No controller execution graph recovered.','boundary':'No private replay state, policy UUID, inferred raw XP or future commands may enter a live policy. Use exact hosted khors for responsive comparisons.'},
      'update':{'revision':1,'guide':'guide-snapshot.md','guide_sha256':sha(OUT/'guide-snapshot.md'),'preserved_prior_models':'evidence/preserved-prior-models.json','new_evidence':['evidence/analysis.json','evidence/clean-control-comparison.json','evidence/own-source-summary.json'],'rejected_overgeneralizations':['Khors always drafts Ranger/Crossbowman','Fewer deaths or fewer zeroes explain its lead','All portals are beneficial','Item19 is a spellbook on the current engine','Longer games always improve points','Our low scores are simply a home-defense lock'],'next_experiments':'counter-hypotheses.ir.json','hosted_games_created':0,'league_changed':False}}
    model['situation']['score_accounting']={'formula':'floor(max(0, lifetime XP - 200 * elapsed minutes))','elapsed_time':'All world ticks, including draft','seven_minute_example':{'xp':1400,'elapsed_minutes':7,'score':0},'interpretation':'An added minute needs more than 200 additional XP to increase the unclamped margin. Existing deficits must be recovered before positive points appear. This is engine accounting, not a recovered khors objective.','evidence':'evidence/mechanics.json'}
    save(OUT/'opponent.ir.json',model);(OUT/'opponent.py').write_text('"""Descriptive opponent MODEL; not a compilable controller."""\nMODEL = '+pprint.pformat(model,width=110,sort_dicts=False)+'\n')
    counter={'schema':'gota-counter-hypotheses-ir/1','parent_source_sha256':plan['source_hashes']['aaron'],'status':'proposed_only_no_policy_changes','opponent_version':plan['ids']['khors'],'goal':'Raise mean individual score while reducing zero/under500frequency and preserving effective ranged play.',
      'hypotheses':[
       {'id':'C114_MELEE_FLOOR','priority':1,'situation':'Low-level melee hero, visible enemy pressure, weak local allied cover','belief':'Our melee9/13zeroes; late ordinal5eight/tenzeroes. Availability often forces these heroes.','skill':'Farm behind allied creeps; retreat before repeated lethal engagements; choose reachable low-risk XP opportunities.','strategy':{'when':'Public class/range and visible local power show a disadvantaged engagement','skill':'SafeMeleeFarm','for':['survive','individual_xp']},'guards':'Do not hardcode actor slot or opponent identity. Preserve killing blows when safely reachable.','validation':'Actual reach/XP-radius fixtures and responsive mixed rosters with late-drafted melee exposure; score+zero-rate+hero/creepXP, not deaths alone.'},
       {'id':'C114_PROGRESS_RELEASE','priority':2,'situation':'Alive/healthy outside keep, no selected target and no visible progress for a bounded period','belief':'Source-reconstructed low-score routes repeatedly advance to enemy base; healthy field droughts recur even with few/no deaths.','skill':'Reevaluate public lane/visible-wave destination and clear stale crossed-route commitment when its purpose is unproductive.','strategy':{'when':'Public no-target/progress timer expires with safe alternatives','skill':'ReacquireProductiveLane','for':['individual_xp']},'guards':'BASIC has no raw XP input. Use validated public proxies such as target absence, landed-hit history, level/gold changes and visible waves. Avoid claiming that gold/hit changes equal XP. Bound oscillation and preserve emergency defense.','validation':'Replay correspondence and public observation fixtures; exact hit/route changes; independent mean score and no-XP intervals, whole-game responsiveness.'},
       {'id':'C114_OBJECTIVE_OPPORTUNITY_COST','priority':3,'situation':'Choice between nearby hero/creep earnings and lengthy structure engagement','belief':'Khors basic structure damage19/game versus ours8466, with more hero/creepXP. Our objective-biased routes can win with zero points. Clean first-draft controls still favor ours, so global structure avoidance is not established.','skill':'Compare feasible hero/creep actions against objective return and travel time; preserve decisive500XPgod finishes.','strategy':{'when':'Public reachable XP opportunities compete with a low-value structure route','skill':'ChooseProductiveOpportunity','for':['individual_xp']},'guards':'Do not prolong a game when marginal XP<200/minute. Avoid copying opponent aggregates as fixed priorities. Prior Richard siege and reward-finisher failures remain rejected.','validation':'Score-centered mixed-roster A/B stratified by hero availability and color; no promotion from win rate or one rival gap alone.'},
       {'id':'C114_OUTBOUND_PORTALS','priority':4,'situation':'Recovered/shopped at keep with a ready scroll and a safe useful friendly destination','belief':'Khors128outbound completions/39 appearances versus ours130/75, but also57keep-to-keep completions and23interruptions.','skill':'Use a destination outside keep to rejoin reachable farming or combat sooner.','strategy':{'when':'Public safe destination meaningfully shortens productive travel','skill':'ReturnToFieldByPortal','for':['individual_xp']},'guards':'Keep existing channel lock, no redundant keep recall, and reserve policy unless independently disproved.','validation':'Accepted endpoint/HP/return-to-XP events and fresh point comparison; more portal starts alone are not success.'},
       {'id':'C114_CAST_AFFORDANCE','priority':5,'situation':'An ability is ready and target is selected, but target reach may exceed that ability','belief':'Ours has~579out-of-range rejections/game versus6.46khors; our R_combat lacks an explicit ability range guard. Rejected casts do not establish lost mana or opportunity.','skill':'Check current-engine ability geometry and select a reachable target when beneficial.','strategy':{'when':'Public target/ability geometry passes a validated cast-affordance test','skill':'CastReachableTarget','for':['individual_xp']},'guards':'Earlier independent spell-pressure confirmation failed; do not repeat it unchanged or equate fewer rejected calls with improved score.','validation':'Accepted damage/healing and alternative-action outcomes, then independent hosted score; all sources and failures preserved.'}],
      'evaluation':'A future implementation needs public-input semantic binding, source/IR round trip, runtime checks, fresh baseline comparisons, both colors and naturally constrained drafts. Report whole-game-correlated uncertainty, personal mean, zero and under500rates, low-case XP, and gaps to khors/Richard/Jordan. No new games scheduled by this analysis.'}
    counter['score_objective']={'formula':'floor(max(0, lifetime XP - 200 * elapsed minutes))','required_diagnostics':['time_cost_xp','unclamped_score_margin','xp_deficit_to_break_even','net_xp_per_minute'],'guard':'Optimize final individual score. Longer games, survival, damage, portal count or XP alone are not advancement gates. Raw XP diagnostics must not leak into live BASIC inputs.'}
    save(OUT/'counter-hypotheses.ir.json',counter)
    save(OUT/'summary.json',{'league_games':72,'khors_appearances':39,'own_appearances':75,'all_vm_clean_games':9,'subjects_failed':0,'own_source_commands_verified':5826,'own_zero_scores':14,'khors_zero_scores':8,'own_melee_zero_scores':9,'own_melee_appearances':13,'own_mean':statistics.mean(r['score'] for r in ours),'khors_mean':statistics.mean(r['score'] for r in khors),'own_nonzero_mean':statistics.mean(r['score'] for r in ours if r['score']>0),'khors_nonzero_mean':statistics.mean(r['score'] for r in khors if r['score']>0),'historical_clean_controls':200,'source_available':False,'proxy_usable':False,'league_changed':False})
    shutil.copy2(Path(__file__).with_name('report-template.md'), OUT/'README.md')

if __name__=='__main__':main()
