"""Generate conservative collision outlines from the supplied atlas alpha."""
from pathlib import Path
from PIL import Image

repository = Path(__file__).resolve().parents[1]
root = repository / 'src/polyworld/treegen'
textures = repository.parent / 'polyworld_data/terrain/treegen'
atlas = Image.open(textures / 'tree-foliage-atlas.png').convert('RGBA')
size = atlas.width // 4

def cross(a, b, c):
    """Return the signed area of a triangle in atlas pixels."""
    return (b[0]-a[0])*(c[1]-a[1]) - (b[1]-a[1])*(c[0]-a[0])

def hull(points):
    """Enclose all opaque texels with a counterclockwise convex polygon."""
    points = sorted(set(points))
    sides = []
    for ordered in (points, reversed(points)):
        side = []
        for point in ordered:
            while len(side) >= 2 and cross(side[-2], side[-1], point) <= 0:
                side.pop()
            side.append(point)
        sides.append(side[:-1])
    return sides[0] + sides[1]

lines = ['import vmath', '', '# Generated by tools/gen_tree_trims.py from the v8 atlas at alpha 0.45.',
         '# Hulls enclose whole opaque texels and use tile-local UV coordinates.',
         'const TrimHulls* = [']
for tile in range(16):
    image = atlas.crop((tile % 4 * size, tile // 4 * size,
                       (tile % 4 + 1) * size, (tile // 4 + 1) * size))
    points = []
    for y in range(size):
        occupied = [x for x in range(size) if image.getpixel((x,y))[3] >= 114]
        if occupied:
            left, right = min(occupied), max(occupied) + 1
            points.extend([(left,y),(right,y),(left,y+1),(right,y+1)])
    outline = hull(points)
    lines.append('  @[')
    for x,y in outline:
        lines.append(f"    vec2({x/size:.8f}'f, {y/size:.8f}'f),")
    lines.append('  ],')
lines.append(']')
(root / 'trims.nim').write_text('\n'.join(lines) + '\n')
